### ISSUE TITLE
Error: ENOENT: no such file or directory, open ''

### ISSUE THREAD

**Issue by oazabir** [atsage/node-red-contrib-nr-ldapauth#1]
Firstly, thanks for creating this node. Just installed the node today. While trying to invoke it using an inject node, getting this error. Any help would be much appreciated. 

```
02/11/2017 10:47:002 Nov 10:47:00 - [error] [node-red-contrib-nr-ldapauth:634b046.2b9c4fc] Error: ENOENT: no such file or directory, open ''
02/11/2017 10:47:00    at Error (native)
02/11/2017 10:47:00    at Object.fs.openSync (fs.js:641:18)
02/11/2017 10:47:00    at Object.fs.readFileSync (fs.js:509:33)
02/11/2017 10:47:00    at new nrldapauth (/data/node_modules/node-red-contrib-nr-ldapauth/nr-ldapauth/nr-ldapauth.js:63:27)
02/11/2017 10:47:00    at createNode (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
02/11/2017 10:47:00    at Flow.start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:89:35)
02/11/2017 10:47:00    at start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:300:29)
02/11/2017 10:47:00    at /usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:137:21
02/11/2017 10:47:00    at tryCatchReject (/usr/src/node-red/node_modules/when/lib/makePromise.js:845:30)
02/11/2017 10:47:00    at runContinuation1 (/usr/src/node-red/node_modules/when/lib/makePromise.js:804:4)
```

**Comment by adonisd** [comment]
It seems the error is generating because of this section in nr-ldapauth.js:

```
		const config = {
			ldap: {

				url: protocol + server + ":" + port,
				adminDn: bindusername,
				adminPassword: bindpassword,
				searchBase: searchbase,
				searchFilter: filter,
				timeout: 2000, /*Doesn't seem to do anything*/
				idleTimeout: 30000, /*Doesn't seem to do anything*/
				tlsOptions: {ca: [ fs.readFileSync(certificatepath) ]},
				reconnect: false /*Doesn't seem to do anything*/

			}
		};
```
It seems, the tlsOptions is being read regardless of LDAP or LDAPS which is causing the problem.
I edited the file manually and commented out tlsOptions and now it's working:
`//tlsOptions: {ca: [ fs.readFileSync(certificatepath) ]},`

**Comment by asage-me** [comment]
Hey, sorry I didn't get any alerts for this issue.  I'll get it fixed and send out an update.  Until then @adonisd's suggestion will work.

**Comment by asage-me** [comment]
Issue should be fixed, pushed to npm
